# Generated by Django 3.0.6 on 2024-11-13 00:55

from django.db import migrations

def create_default_org(apps, schema_editor):
    # Create a default organization to initialize Organization table
    Organization = apps.get_model("login", "Organization")
    org = Organization(name = "Default", description = "Default")
    org.save()

class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_organization'),
    ]

    operations = [
        migrations.RunPython(create_default_org),
    ]