# Generated by Django 3.0.6 on 2024-11-13 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0001_initial'),
        ('hospital', '0001_initial'),
        ('equipment', '0001_initial'),
        ('login', '0003_auto_20241113_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='ambulances',
            field=models.ManyToManyField(to='ambulance.Ambulance'),
        ),
        migrations.AddField(
            model_name='organization',
            name='equipment_set',
            field=models.ManyToManyField(to='equipment.EquipmentSet'),
        ),
        migrations.AddField(
            model_name='organization',
            name='hospital',
            field=models.ManyToManyField(to='hospital.Hospital'),
        ),
    ]