# Generated by Django 3.0.6 on 2024-11-20 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20241113_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupprofile',
            name='organization',
            # Establish default to avoid requiring user input on startup.
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.Organization', verbose_name='organization'),
        ),
    ]